services:
  - type: web
    name: portfolio-rails8
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate"
    startCommand: "bundle exec rails server -p $PORT -e production"